spring:
  application:
    name: rest-udemy-2025
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    root: INFO
    com.github.paulocarpinetti: DEBUG
spring-doc:
  paths-to-match:
    - /**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true
